name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-petclinic-name:latest
    - name: Deploy the Docker image
      run: docker run -p 8080:8080 springcommunity/spring-framework-petclinic
